name: news_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.1.2

  # Comparing Dart objects
  equatable: ^2.0.5

  # Service locator
  get_it: ^7.6.0

  # Date format
  intl: ^0.18.1

  # Database
  floor: ^1.4.2

  # Make API calls
  retrofit: ^3.0.1

  # Hooks functions
  flutter_hooks: ^0.18.3

  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0
  retrofit_generator: 3.0.1+1
  floor_generator: 1.2.0
  build_runner: 2.1.2

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
   - family: Muli
     fonts:
       - asset: assets/fonts/Muli.ttf
       - asset: assets/fonts/Muli-Bold.ttf
         weight: 700
       - asset: assets/fonts/Muli-Light.ttf
         weight: 300
